#!/bin/bash

# Run this script from the 'LEGOv2' directory to convert dialogs to Au format 
# and store them in 'output_dir'
output_dir=recordings
mkdir -p $output_dir
find . -name '*input_and_output.wav' -exec bash -c 'sox "$0" $1/$(basename "$0" .wav).au' {} $output_dir \;